config/routes.rb
Rails.application.routes.draw do

  resources :withdrawal_requests, :except => [:new, :edit]
  resources :bookings, :except => [:edit]

  # Rate Button
  post 'rate', to: 'bookings#rate'

  # Booking Time Search
  post 'timesearch', to: 'map#timesearch'
  post 'clearsearch', to: 'map#clearsearch'

  # Homeowner and Driver Booking Lists
  get 'homeowner_bookings', to: 'bookings#homeowner_bookings'
  get 'driver_bookings', to: 'bookings#driver_bookings'

  resources :drivers
  resources :homeowners
  devise_for :users
  get 'contact', to:'home#contact'
  get 'privacy', to: 'home#privacy'
  post 'request_contact', to: 'home#request_contact'

  # Sign Up View
  get 'signup', to:'home#signup'

  # App Root
  root 'map#map'


  # Verification Form
  get 'verification', to:'verification#new'
  post 'verification', to:'verification#verify'

  # Omniauth Redirect
  get '/auth/:provider/callback' => 'home#omniauth'

  # Omniauth Cancel Redirect
  get '/auth/failure', to: 'map#map'

  # Temporary error route
  get 'booking_error', to: 'home#booking_error'

  # Routes for scheduler
  get "data", :to=>"scheduler#get", :as=>"data"
  post "data(/:id)", :to => "scheduler#add"
  put "data/:id", :to => "scheduler#update"
  delete "data/:id", :to => "scheduler#delete"

  # Stripe routes
  scope '/charges' do
    post 'create', to: 'charges#create', as: 'charges_create'
    post 'refund', to: 'charges#refund', as: 'charges_refund'
    get 'cancel', to: 'charges#cancel', as: 'charges_cancel'
    get 'success', to: 'charges#success', as: 'charges_success'
  end

  # Temporary live chat route
  get 'chat', to:'chat#chat'

  # Create Withdrawal Request
  post 'withdraw', to: 'withdrawal_requests#withdraw', as: 'withdraw'

  # Process Withdrawal Request
  post 'process_request', to: 'withdrawal_requests#process_request', as: 'process_request'

  # Resources for chat
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/homeowner.rb
class Homeowner < ApplicationRecord
  belongs_to :user

  has_many :bookings, dependent: :destroy
  has_many :withdrawal_requests, dependent: :destroy

  validates :address, uniqueness: true

  validates :address, :latitude, :longitude, :paypal_email, :driveway_description, :driveway_price, presence: true
  validates :driveway_price, numericality: {greater_than: 0, less_than_or_equal_to: 100}
end

app/controllers/homeowners_controller.rb
class HomeownersController < ApplicationController
  before_action :set_homeowner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_homeowner_check, only: [:show, :edit, :update, :destroy]

  # GET /homeowners
  # GET /homeowners.json
  def index
    admin_check
    @homeowners = Homeowner.all
  end

  # GET /homeowners/1
  # GET /homeowners/1.json
  def show
  end

  # GET /homeowners/new
  def new
    if Homeowner.exists?(user_id: current_user.id)
      @homeowner = Homeowner.find_by_user_id(current_user.id)
      redirect_to "/homeowners/#{@homeowner.id}"
    end
    @homeowner = Homeowner.new
  end

  # GET /homeowners/1/edit
  def edit
    unless @homeowner.driveway_verified
      redirect_to @homeowner, alert: "Your driveway isn't verified yet!"
    end
  end

  # POST /homeowners
  # POST /homeowners.json
  def create
    @homeowner = Homeowner.new(homeowner_params)
    @homeowner.user_id = current_user.id
    @homeowner.activation_code = (0...8).map { (65 + rand(26)).chr }.join
    @homeowner.last_modified = Date.today

    respond_to do |format|
      if @homeowner.save
        HomeownerMailer.homeowner_confirmation(@homeowner).deliver_now
        format.html { redirect_to @homeowner, notice: 'Driveway registered successfully. Please check your email for the verification code!' }
        format.json { render :show, status: :created, location: @homeowner }
      else
        format.html { render :new }
        format.json { render json: @homeowner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeowners/1
  # PATCH/PUT /homeowners/1.json
  def update
    respond_to do |format|
      if @homeowner.update(homeowner_params)
        format.html { redirect_to @homeowner, notice: 'Details updated successfully.' }
        format.json { render :show, status: :ok, location: @homeowner }
      else
        format.html { render :edit }
        format.json { render json: @homeowner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeowners/1
  # DELETE /homeowners/1.json
  def destroy
    @homeowner.destroy
    respond_to do |format|
      format.html { redirect_to homeowners_url, notice: 'Homeowner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def admin_check
      unless current_user.admin?
        redirect_to root_path, alert: "You do not have admin privileges!"
      end
    end

    def correct_homeowner_check
      unless current_user.admin?
        if Homeowner.exists?(user_id: current_user.id)
          if params[:id].to_i != Homeowner.find_by_user_id(current_user.id).id
            flash[:alert] = "You cannot access another homeowner's Information!"
            redirect_to root_path
            return
          end
        else
          flash[:alert] = "You are not signed up as a homeowner!"
          redirect_to root_path
          return
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_homeowner
      @homeowner = Homeowner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def homeowner_params
      params.require(:homeowner).permit(:user_id, :address, :latitude, :longitude, :driveway_description, :driveway_price, :last_modified, :activation_code, :driveway_verified, :total_ratings, :number_ratings, :paypal_email, :active_start, :active_end)
    end
end

app/helpers/homeowners_helper.rb
module HomeownersHelper
end

app/views/homeowners/_form.html.erb
<%#= form_with(model: homeowner, local: true) do |form| %>
  <%# if homeowner.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(homeowner.errors.count, "error") %> prohibited this homeowner from being saved:</h2>-->

<!--      <ul>-->
        <%# homeowner.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>
<!--  </div>-->



  <%# provide :head_tags do %>
<!--    <meta name='turbolinks-visit-control' content='reload'>-->
<!--    <script>-->
<!--        document.addEventListener("DOMContentLoaded", initMap2);-->
<!--    </script>-->
  <%# end %>


<!--  <div id="map-holder">-->
<!--    <div id="map2"></div>-->

    <%#= form.hidden_field :latitude %>

    <%#= form.hidden_field :longitude %>







<!--    <div id="right-div">-->
      <%#= form.label :address %>
      <%#= form.text_area :address %>


        <%#= form.label :driveway_description %>
        <%#= form.text_area :driveway_description %>



        <%#= form.label :driveway_price %>
        <%#= form.text_field :driveway_price %>
<!--      </div>-->

        <%#= form.label :driveway_active %>
        <%#= form.check_box :driveway_active %>


        <%#= form.submit %>



<!--    </div>-->


<%# end %>

<div id="left-div">


  <%= form_with(model: homeowner, local: true) do |form| %>
  <% if homeowner.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(homeowner.errors.count, "error") %> prohibited this homeowner from being saved:</h2>

        <ul>
  <% homeowner.errors.full_messages.each do |message| %>
            <li><%= message %></li>
  <% end %>
        </ul>
      </div>
  <% end %>
    </div>



  <% provide :head_tags do %>
      <meta name='turbolinks-visit-control' content='reload'>
      <script>
          document.addEventListener("DOMContentLoaded", initMap2);
      </script>
  <% end %>


    <div id="map-holder">
      <div id="map2"></div>


  <%= form.hidden_field :latitude %>

  <%= form.hidden_field :longitude %>












</div>
<div id="right-div">



  <div class="label" style="font-size: 22px;"><%= form.label :address %></div>

  <div id="input-div"><%= form.text_area :address, class: "textarea" %></div>


  <div class="label" style="font-size: 22px;"><%= form.label :driveway_description %></div>
  <div id="input-div"><%= form.text_area :driveway_description, class: "textarea"%></div>



  <div class="label" style="font-size: 22px;"><%= form.label :driveway_price %></div>
  <div id="input-div"><%= form.text_field :driveway_price, class: "input is-large" %></div>


    <div class="label"><%= form.label :driveway_active, class: "checkbox-label"%><%= form.check_box :driveway_active, class: "checkbox" %></div>
  <p id="useful-tip">THIS SPACE CAN BE USED TO HAVE A USEFUL TIP</p>


  <div style="margin-top: 5%;"><%= form.submit :submit_button, class: "button is-primary is-large"%></div>



<% end %>
</div>

app/views/homeowners/edit.html.erb
<div class="columns has-text-centered is-gapless is-multiline">
  <div class="column is-two-thirds">
    <%= form_with(model: @homeowner, local: true) do |form| %>
      <% if @homeowner.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@homeowner.errors.count, "error") %> prohibited this homeowner from being saved:</h2>

          <ul>
            <% @homeowner.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <h1 class="title">Edit Driveway Details</h1>
        <div class="field">
          <%= form.label :paypal_email %>
          <br>
          <%= form.text_field(:paypal_email, :class => 'input') %>
        </div>

        <div class="field">
          <%= form.label :address %>
          <br>
          <%= form.text_field(:address, :class => 'input', :readonly => true) %>
        </div>

        <div class="field">
          <%= form.label :driveway_description %>
          <br>
          <%= form.text_field(:driveway_description, :class => 'input') %>
        </div>

        <div class="field">
          <%= form.label "Driveway Price Per Hour (£/hr)" %>
          <br>
          <%= form.text_field(:driveway_price, :class => 'input') %>
        </div>

        <div class="field">
          <%= form.label :active_start %>
          <%= form.datetime_select :active_start, {datetime_separator: " at ", :minute_step => 60, :discard_minute => true}, class: "select" %>:00
        </div>

        <div class="field">
          <%= form.label :active_end %>
          <%= form.datetime_select :active_end, {datetime_separator: " at ", :minute_step => 60, :discard_minute => true}, class: "select" %>:00
        </div>

        <div class="actions">
          <%= form.submit "Confirm Changes", ({class: "button is-primary is-large"}) %>
        </div>
    <% end %>
    </div>
  </div>
  <div class="column">
    <div class="box is-rounded">
      <figure class="image"><%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=18&size=400x300&markers=size:small%7Ccolor:red%7C#{@homeowner.latitude},#{@homeowner.longitude}&key=#{Rails.application.credentials.google[:google_maps_api_key]}", alt: "Map" %></figure>
    </div>
  </div>
</div>

app/views/homeowners/index.html.erb
<div class="has-text-centered">
  <h1 class="title">Homeowners</h1>
  <div style="overflow-x: auto;">
    <table class="table is-striped is-hoverable is-fullwidth">
      <thead>
      <tr>
        <th>User</th>
        <th>Address</th>
        <th>Description</th>
        <th>Price</th>
        <th>Last modified</th>
        <th>Code</th>
        <th>Verified</th>
        <th>Average Rating</th>
        <th>Active Start</th>
        <th>Active End</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @homeowners.each do |homeowner| %>
        <tr>
          <td><%= homeowner.user.name %></td>
          <td><%= homeowner.address %></td>
          <td><%= homeowner.driveway_description %></td>
          <td><%= number_to_currency(homeowner.driveway_price, unit:"£") %></td>
          <td><%= homeowner.last_modified %></td>
          <td><%= homeowner.activation_code %></td>
          <td><%= homeowner.driveway_verified %></td>
          <td>
            <% if homeowner.total_ratings == 0 %>
              No Ratings Yet
            <% else %>
              <%= (homeowner.total_ratings.to_f / homeowner.number_ratings).round(2) %>
            <% end %>
          </td>
          <td><%= homeowner.active_start %></td>
          <td><%= homeowner.active_end %></td>
          <td><%= link_to 'Show', homeowner, :class => 'button' %></td>
          <td><%= link_to 'Edit', edit_homeowner_path(homeowner), :class => 'button is-info' %></td>
          <td><%= link_to 'Destroy', homeowner, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'button is-danger' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/homeowners/new.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", initMapHO);
  </script>
<% end %>

<div class="columns has-text-centered is-gapless">
  <div class="column">
    <h1 class="title">New Driveway</h1>
    <%= form_with(model: @homeowner, local: true) do |form| %>
      <% if @homeowner.errors.any? %>
        <div id="error_explanation">
          <h2>Please check these <%= pluralize(@homeowner.errors.count, "field") %>:</h2>
          <ul>
            <% @homeowner.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <h1 class="subtitle is-marginless is-size-4">Locate Driveway</h1>
      <div class="field">
        <%= form.label :enter_address, "1. Enter address" %>
        <br>
        <input id="pac-input" class=" input" type="text" placeholder="Search address and drag to driveway">
      </div>
      <div class="field" style="display: none;">
        <%= form.label :address %>
        <br>
        <%= form.text_field(:address, :class => 'input', :readonly => true) %>
      </div>
      <p style="font-size: 18px">2. Drag the pin within the red square to the centre of your driveway.</p><br>
      <div class="field" style="display: none">
        <%= form.label :latitude %>
        <br>
        <%= form.text_field :latitude, :readonly => true %>
      </div>
      <div class="field" style="display: none">
        <%= form.label :longitude %>
        <br>
        <%= form.text_field :longitude, :readonly => true %>
      </div>
      <h1 class="subtitle is-marginless is-size-4">Driveway Details</h1>
      <div class="field">
        <%= form.label :driveway_description %>
        <br>
        <%= form.text_field(:driveway_description, :class => 'input') %>
      </div>
      <div class="field">
        <%= form.label "Driveway Price Per Hour (£)" %>
        <br>
        <%= form.text_field(:driveway_price, :class => 'input') %>
      </div>

      <div class="field">
        <%= form.label :paypal_email %>
        <br>
        <%= form.text_field(:paypal_email, :class => 'input') %>
      </div>

      <div class="actions">
        <%= form.submit({class: "button is-primary is-large", value: "Register Driveway"}) %>
      </div>
    <% end %>
  </div>
  <div class="column">
    <div class="box">
      <div id="map2"></div>
      <h1 class="subtitle">Use this map for step 2.</h1>
    </div>
  </div>
</div>

app/views/homeowners/show.html.erb
<div class="columns is-gapless is-multiline">
  <div class="column has-text-centered is-two-thirds">
    <h1 class="title">Your Driveway</h1>
    <div id="square">

      <p>
        <strong>
          <% if @homeowner.driveway_verified %>
            Driveway is Verified
          <% else %>
            Not Verified (verification code is sent to your email)
          <% end %>
        </strong>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @homeowner.address %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @homeowner.driveway_description %>
      </p>

      <p>
        <strong>Price Per Hour:</strong>
        <%= number_to_currency(@homeowner.driveway_price, unit: "£") %>
      </p>

      <p>
        <strong>Average Rating:</strong>
        <% if @homeowner.number_ratings == 0 %>
          No Ratings Yet
        <% else %>
          <%= (@homeowner.total_ratings.to_f / @homeowner.number_ratings).round(2) %>/5
        <% end %>
      </p>

      <p>
        <strong>PayPal Email:</strong>
        <%= @homeowner.paypal_email %>
      </p>

      <% if @homeowner.active_start.nil? %>
        <p class="has-text-danger">
          Your driveway isn't available to drivers yet.
        </p>
      <% else %>
        <% if Time.now > @homeowner.active_start and Time.now < @homeowner.active_end %>
          <p class="has-text-success">
            Your driveway is available to drivers and active until <%= @homeowner.active_end.strftime("%F at %T") %>
          </p>
        <% else %>
          <p class="has-text-danger">
            Your driveway is currently inactive!
          </p>
        <% end %>
      <% end %>

      <div>
        <% if @homeowner.driveway_verified %>
          <%= link_to 'Enter Availability / Edit Details', edit_homeowner_path(@homeowner), :class => 'button is-primary is-medium' %>
        <% else %>
          <%= link_to 'Verify Driveway', verification_path, :class => 'button is-success' %>
        <% end %>

      </div>
    </div>
  </div>
  <div class="column">
    <div class="box is-rounded">
      <figure class="image"><%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=18&size=600x600&markers=size:small%7Ccolor:red%7C#{@homeowner.latitude},#{@homeowner.longitude}&key=#{Rails.application.credentials.google[:google_maps_api_key]}", alt: "Map" %></figure>
    </div>
  </div>
</div>