config/routes.rb
Rails.application.routes.draw do

  resources :withdrawal_requests, :except => [:new, :edit]
  resources :bookings, :except => [:edit]

  # Rate Button
  post 'rate', to: 'bookings#rate'

  # Booking Time Search
  post 'timesearch', to: 'map#timesearch'
  post 'clearsearch', to: 'map#clearsearch'

  # Homeowner and Driver Booking Lists
  get 'homeowner_bookings', to: 'bookings#homeowner_bookings'
  get 'driver_bookings', to: 'bookings#driver_bookings'

  resources :drivers
  resources :homeowners
  devise_for :users
  get 'contact', to:'home#contact'
  get 'privacy', to: 'home#privacy'
  post 'request_contact', to: 'home#request_contact'

  # Sign Up View
  get 'signup', to:'home#signup'

  # App Root
  root 'map#map'


  # Verification Form
  get 'verification', to:'verification#new'
  post 'verification', to:'verification#verify'

  # Omniauth Redirect
  get '/auth/:provider/callback' => 'home#omniauth'

  # Omniauth Cancel Redirect
  get '/auth/failure', to: 'map#map'

  # Temporary error route
  get 'booking_error', to: 'home#booking_error'

  # Routes for scheduler
  get "data", :to=>"scheduler#get", :as=>"data"
  post "data(/:id)", :to => "scheduler#add"
  put "data/:id", :to => "scheduler#update"
  delete "data/:id", :to => "scheduler#delete"

  # Stripe routes
  scope '/charges' do
    post 'create', to: 'charges#create', as: 'charges_create'
    post 'refund', to: 'charges#refund', as: 'charges_refund'
    get 'cancel', to: 'charges#cancel', as: 'charges_cancel'
    get 'success', to: 'charges#success', as: 'charges_success'
  end

  # Temporary live chat route
  get 'chat', to:'chat#chat'

  # Create Withdrawal Request
  post 'withdraw', to: 'withdrawal_requests#withdraw', as: 'withdraw'

  # Process Withdrawal Request
  post 'process_request', to: 'withdrawal_requests#process_request', as: 'process_request'

  # Resources for chat
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div id="footer-bottom">
  <% unless user_signed_in? %>
    <%= link_to "Click Here To Sign Up", '/auth/google_oauth2', class: "button is-primary is-fullwidth is-large" %>
  <% end %>

  <div class="level">
    <div class="level-item is-marginless"><%= link_to 'Contact Us', contact_path %></div>
    <div class="level-item"><%= link_to 'Privacy Policy', privacy_path %></div>
  </div>
</div>

app/views/shared/_header.html.erb
<%
  current_homeowner = nil
  current_driver = nil

  if user_signed_in?
    if Homeowner.exists?(user_id: current_user.id)
      current_homeowner = Homeowner.find_by_user_id(current_user.id)
    end
    if Driver.exists?(user_id: current_user.id)
      current_driver = Driver.find_by_user_id(current_user.id)
    end
  end
%>

<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">

    <% if user_signed_in? %>
      <a href="/">
        <%= image_tag("logo_paypark.png", size: "55x450", :class => "nav-image") %>
      </a>
    <% else %>
      <a href="/users/sign_in">
        <%= image_tag("logo_paypark.png", size: "55x450", :class => "nav-image") %>
      </a>
      <div class="navbar-item is-size-4">
        PayPark
      </div>
    <% end %>


    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
      <span aria-hidden="true" style="color: white"></span>
      <span aria-hidden="true" style="color: white"></span>
      <span aria-hidden="true" style="color: white"></span>


    </a>


  </div>

  <div class="navbar-menu">
    <div class="navbar-start">

      <% if user_signed_in? %>

        <%= link_to " <i class='fas fa-search-location fa-lg'></i> &nbsp Find Parking".html_safe, root_path, :class => "navbar-item" %>
        <% unless current_homeowner.nil? and current_driver.nil? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link"><i class="fas fa-calendar-check fa-lg"></i>&nbspAll Bookings</a>

            <div class="navbar-dropdown">
              <% unless current_homeowner.nil? %>
                <%= link_to " <i class='fas fa-clipboard-list'></i> &nbsp On My Driveway".html_safe, homeowner_bookings_path, :class => "navbar-item" %>
              <% end %>

              <% unless current_driver.nil? %>
                <%= link_to " <i class='fas fa-book'></i> &nbspMy Bookings".html_safe, driver_bookings_path, :class => "navbar-item" %>
              <% end %>

              <% unless current_driver.nil? and current_homeowner.nil? %>
                <%= link_to " <i class='fas fa-comments'></i> &nbspChat".html_safe, chat_path, :class => "navbar-item" %>
              <% end %>
            </div>
          </div>
        <% end %>

        <% unless current_homeowner.nil? %>
          <%= link_to " <i class='fas fa-home fa-lg'></i> &nbspMy Driveway".html_safe, current_homeowner, :class => "navbar-item" %>
        <% end %>

        <% unless current_driver.nil? %>
          <%= link_to " <i class='fas fa-car fa-lg'></i> &nbspMy Vehicle".html_safe, current_driver, :class => "navbar-item" %>
        <% end %>
      <% end %>
    </div>


    <div class="navbar-end">
      <% if user_signed_in? %>

        <% if current_homeowner.nil? %>
          <%= link_to " <i class='fas fa-home '></i> &nbsp Register Driveway".html_safe, new_homeowner_path, :class => "navbar-item" %>
        <% end %>

        <% if current_driver.nil? %>
          <%= link_to " <i class='fas fa-car'></i> &nbsp Add Car Info".html_safe, new_driver_path, :class => "navbar-item" %>
        <% end %>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link"><%= current_user.admin ? "Admin | " + current_user.name : current_user.name %></a>
          <div class="navbar-dropdown is-right">
            <%= link_to " <i class='fas fa-user'></i> &nbsp My Account".html_safe, edit_user_registration_path, :class => "navbar-item" %>

            <% if current_user.admin? %>
              <hr class="navbar-divider">
              <%= link_to "All Homeowners", homeowners_path, :class => "navbar-item" %>
              <%= link_to "All Drivers", drivers_path, :class => "navbar-item" %>
              <%= link_to "All Bookings", bookings_path, :class => "navbar-item" %>
              <%= link_to "Withdrawal Requests", withdrawal_requests_path, :class => "navbar-item" %>
            <% end %>

            <%= link_to " <i class='fas fa-sign-out-alt'></i> &nbsp Logout".html_safe, destroy_user_session_path, method: 'delete', :class => "navbar-item" %>
          </div>
        </div>

      <% else %>
        <div class="buttons">
          <%= link_to " <i class='fas fa-sign-in-alt'></i> &nbsp Login/Signup".html_safe, '/auth/google_oauth2', :class => "button is-primary", :id => "login-button" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>
<script>
    window.onscroll = function () {
        myFunction()
    };

    var navbar = document.getElementById("navbar");
    var sticky = navbar.offsetTop;

    function myFunction() {
        if (window.pageYOffset >= sticky) {
            navbar.classList.add("sticky")
        } else {
            navbar.classList.remove("sticky");
        }
    }
</script>
<script>
    $(document).ready(function () {

        // Check for click events on the navbar burger icon
        $(".navbar-burger").click(function () {

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");

        });
    });
</script>