config/routes.rb
Rails.application.routes.draw do

  resources :withdrawal_requests, :except => [:new, :edit]
  resources :bookings, :except => [:edit]

  # Rate Button
  post 'rate', to: 'bookings#rate'

  # Booking Time Search
  post 'timesearch', to: 'map#timesearch'
  post 'clearsearch', to: 'map#clearsearch'

  # Homeowner and Driver Booking Lists
  get 'homeowner_bookings', to: 'bookings#homeowner_bookings'
  get 'driver_bookings', to: 'bookings#driver_bookings'

  resources :drivers
  resources :homeowners
  devise_for :users
  get 'contact', to:'home#contact'
  get 'privacy', to: 'home#privacy'
  post 'request_contact', to: 'home#request_contact'

  # Sign Up View
  get 'signup', to:'home#signup'

  # App Root
  root 'map#map'


  # Verification Form
  get 'verification', to:'verification#new'
  post 'verification', to:'verification#verify'

  # Omniauth Redirect
  get '/auth/:provider/callback' => 'home#omniauth'

  # Omniauth Cancel Redirect
  get '/auth/failure', to: 'map#map'

  # Temporary error route
  get 'booking_error', to: 'home#booking_error'

  # Routes for scheduler
  get "data", :to=>"scheduler#get", :as=>"data"
  post "data(/:id)", :to => "scheduler#add"
  put "data/:id", :to => "scheduler#update"
  delete "data/:id", :to => "scheduler#delete"

  # Stripe routes
  scope '/charges' do
    post 'create', to: 'charges#create', as: 'charges_create'
    post 'refund', to: 'charges#refund', as: 'charges_refund'
    get 'cancel', to: 'charges#cancel', as: 'charges_cancel'
    get 'success', to: 'charges#success', as: 'charges_success'
  end

  # Temporary live chat route
  get 'chat', to:'chat#chat'

  # Create Withdrawal Request
  post 'withdraw', to: 'withdrawal_requests#withdraw', as: 'withdraw'

  # Process Withdrawal Request
  post 'process_request', to: 'withdrawal_requests#process_request', as: 'process_request'

  # Resources for chat
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact
  end

  def booking_error
  end

  def privacy
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank? or name.blank? or message.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')

    else
      # Send an email
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
      redirect_to root_path
      return
    end
    redirect_to contact_path, notice: "There was a problem"

  end


  def omniauth
    puts "AUTH STUFF: #{auth.inspect}"
    @user = User.from_omniauth(auth)

    puts "USER STUFF: #{User.from_omniauth(auth).inspect} Name:#{@user.name} Email:#{@user.email} "
    # Find token
    token = @user.tokens.find_or_initialize_by(provider: 'google')
    # Access_token is used to authenticate requests
    token.access_token = auth.credentials.token
    token.expires_at = auth.credentials.expires_at
    puts "ACCESS TOKEN EXPIRES IN #{token.expires_at}"
    # Refresh_token to request new access_token
    # Note: Refresh_token is only sent once during the first request
    refresh_token = auth.credentials.refresh_token
    token.refresh_token = refresh_token if refresh_token.present?
    # save token
    token.save

    @user.save
    sign_in(User.find(@user.id), scope: :user)

    if !Homeowner.exists?(user_id: current_user.id) && !Driver.exists?(user_id: current_user.id)
      redirect_to signup_path
    else
      redirect_to root_path
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/booking_error.html.erb
<div id="overall-container">
<h1>Error!</h1>
<p> Bookings must be placed at least an hour later than the current time, <br>
  and must not conflict with any other bookings. </p>

<a href="/">Back to map</a>
</div>

app/views/home/contact.html.erb
<div class="has-text-centered">
  <h1 class="title">
    <%= t('.title') %>
  </h1>

  <p class="subtitle">
    <%= t('.contact_us') %>
  </p>

  <%= form_tag request_contact_path, method: 'post' do %>

    <%= label_tag :name, t('.name'), :class => "subtitle" %>

    <br>

    <%= text_field_tag :name, '', title: t('.enter_name'), size: 50, value: user_signed_in? ? current_user.name : "", class: "input" %>

    <br>

    <%= label_tag :email, t('.email'), :class => "subtitle" %>

    <br>

    <%= email_field_tag :email, '', title: t('.enter_email'), value: user_signed_in? ? current_user.email : "", :class => "input" %>

    <br>

    <%= label_tag :telephone, t('.telephone'), :class => "subtitle" %>

    <br>

    <%= telephone_field_tag :telephone, '', title: t('.enter_telephone'), :class => "input" %>

    <br>

    <%= label_tag :message, t('.message'), :class => "subtitle" %>

    <br>

    <%= text_area_tag :message, '', title: t('.enter_message'), :class => "textarea", :rows => 5 %>

    <br>
    <% flash.each do |key, value| %>
      <%= content_tag :div, content_tag(:p, value), :class => "subtitle is-info", id: "#{key}" unless value.blank? %>
    <% end %>
    <br>

    <%= submit_tag t('.submit'), :class => "button is-primary is-large" %>

  <% end %>
</div>

<% 3.times do %>
  <br>
<% end %>

app/views/home/privacy.html.erb
<h1 class="title has-text-centered">Privacy Policy</h1>
<p class="has-text-justified">Your privacy is important to us. It is PayPark's policy to respect your privacy regarding
  any information we may
  collect from you across our website,
  <a href="https://paypark-group24.herokuapp.com/" class="has-text-black">https://paypark-group24.herokuapp.com/</a>,
  and other sites we
  own and operate.
  We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and
  lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be
  used.
  We only retain collected information for as long as necessary to provide you with your requested service. What
  data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as
  unauthorised access, disclosure, copying, use or modification.
  We don’t share any personally identifying information publicly or with third-parties, except when required to by
  law.
  Our website may link to external sites that are not operated by us. Please be aware that we have no control over
  the content and practices of these sites, and cannot accept responsibility or liability for their respective
  privacy policies.
  You are free to refuse our request for your personal information, with the understanding that we may be unable to
  provide you with some of your desired services.
  Your continued use of our website will be regarded as acceptance of our practices around privacy and personal
  information. If you have any questions about how we handle user data and personal information, feel free to
  contact us. As a commission, PayPark will deduct 10% of prices of all bookings completed through the website. This
  policy is effective as of 25 May 2020.</p>
<% 3.times do %>
  <br>
<% end %>

app/views/home/signup.html.erb
<div class="has-text-centered">
  <h1 class="title">Sign Up</h1>
  <h2 class="subtitle">Would you like to be a homeowner or a driver?</h2>
  <%= link_to " <i class='fas fa-car-side fa-lg'></i> &nbsp Driver".html_safe, new_driver_path, :class => "button is-danger is-outlined is-large" %>
  <%= link_to " <i class='fas fa-home fa-lg'></i> &nbsp Homeowner".html_safe, new_homeowner_path, :class => "button is-info is-outlined is-large" %>
</div>