config/routes.rb
Rails.application.routes.draw do

  resources :withdrawal_requests, :except => [:new, :edit]
  resources :bookings, :except => [:edit]

  # Rate Button
  post 'rate', to: 'bookings#rate'

  # Booking Time Search
  post 'timesearch', to: 'map#timesearch'
  post 'clearsearch', to: 'map#clearsearch'

  # Homeowner and Driver Booking Lists
  get 'homeowner_bookings', to: 'bookings#homeowner_bookings'
  get 'driver_bookings', to: 'bookings#driver_bookings'

  resources :drivers
  resources :homeowners
  devise_for :users
  get 'contact', to:'home#contact'
  get 'privacy', to: 'home#privacy'
  post 'request_contact', to: 'home#request_contact'

  # Sign Up View
  get 'signup', to:'home#signup'

  # App Root
  root 'map#map'


  # Verification Form
  get 'verification', to:'verification#new'
  post 'verification', to:'verification#verify'

  # Omniauth Redirect
  get '/auth/:provider/callback' => 'home#omniauth'

  # Omniauth Cancel Redirect
  get '/auth/failure', to: 'map#map'

  # Temporary error route
  get 'booking_error', to: 'home#booking_error'

  # Routes for scheduler
  get "data", :to=>"scheduler#get", :as=>"data"
  post "data(/:id)", :to => "scheduler#add"
  put "data/:id", :to => "scheduler#update"
  delete "data/:id", :to => "scheduler#delete"

  # Stripe routes
  scope '/charges' do
    post 'create', to: 'charges#create', as: 'charges_create'
    post 'refund', to: 'charges#refund', as: 'charges_refund'
    get 'cancel', to: 'charges#cancel', as: 'charges_cancel'
    get 'success', to: 'charges#success', as: 'charges_success'
  end

  # Temporary live chat route
  get 'chat', to:'chat#chat'

  # Create Withdrawal Request
  post 'withdraw', to: 'withdrawal_requests#withdraw', as: 'withdraw'

  # Process Withdrawal Request
  post 'process_request', to: 'withdrawal_requests#process_request', as: 'process_request'

  # Resources for chat
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/map_controller.rb
require 'google/api_client/client_secrets.rb'
require 'google/apis/calendar_v3'
class MapController < ApplicationController
  before_action :authenticate_user!

  def map
    unless  session[:booking_start_time].nil? and session[:booking_end_time].nil?
      gon.driveways = Homeowner.where("active_start < ? and active_end > ? and driveway_verified = ?", session[:booking_start_time].to_datetime, session[:booking_end_time].to_datetime, true)
    else
      gon.driveways = Homeowner.where("active_start < ? and active_end > ? and driveway_verified = ?", DateTime.now, DateTime.now, true)
    end

    begin
      Google::Apis.logger = Logger.new(nil)
      token = current_user.google_token
      # Initialize Google Calendar API
      service = Google::Apis::CalendarV3::CalendarService.new
      # Use google keys to authorize
      service.authorization = token.google_secret.to_authorization
      # Request for a new access token just incase it expired
      if token.expired?
        new_access_token = service.authorization.refresh!
        token.access_token = new_access_token['access_token']
        token.expires_at = Time.now.to_i + new_access_token['expires_in'].to_i
        token.save
      end

      # Fetch the next 10 events for the user
      calendar_id = "primary"
      @response = service.list_events(calendar_id, max_results: 10, single_events: true, order_by: "startTime", time_min: DateTime.now.rfc3339)
    rescue StandardError => e
      @response = "You have not given the website permissions!"
    end
  end

  def timesearch
    if params[:start_time].blank? or params[:end_time].blank?
      flash[:alert] = "Please fill in a start and end time."
      redirect_to root_path
      return
    end


    start_time = DateTime.new(params[:start_time]["start_time(1i)"].to_i, params[:start_time]["start_time(2i)"].to_i, params[:start_time]["start_time(3i)"].to_i, params[:start_time]["start_time(4i)"].to_i)
    end_time = DateTime.new(params[:end_time]["end_time(1i)"].to_i, params[:end_time]["end_time(2i)"].to_i, params[:end_time]["end_time(3i)"].to_i, params[:end_time]["end_time(4i)"].to_i)

    session[:booking_start_time] = start_time
    session[:booking_end_time] = end_time
    redirect_to root_path
  end

  def clearsearch
    session[:booking_start_time]=nil
    session[:booking_end_time]=nil
    redirect_to root_path
  end

end

app/helpers/map_helper.rb
module MapHelper
end

app/views/map/map.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", function () {
          initMap()
      });
  </script>
<% end %>

<div class="columns is-gapless">
  <div class="column is-four-fifths">
    <div class="box">
      <div class="box subtitle is-marginless has-text-centered">
        Showing driveways
        <% if session[:booking_start_time].nil? and session[:booking_end_time].nil? %>
          currently available.
        <% else %>
          available between <%= session[:booking_start_time].to_datetime.strftime("%F at %T") %>
          until <%= session[:booking_end_time].to_datetime.strftime("%F at %T") %>
          <%= link_to 'Clear Times', clearsearch_path, method: :post, :class => "button is-small is-danger" %>
        <% end %>
      </div>
      <input id="pac-input" class="input has-text-centered" type="text" placeholder="Search address">
      <div id="map"></div>
    </div>

  </div>

  <div class="column has-text-centered">
    <h2 class="title is-marginless has-text-centered">Find Parking</h2>

    <div class="dropdown is-hoverable">
      <div class="dropdown-trigger">
        <button class="button" aria-haspopup="true" aria-controls="dropdown-menu3">
          <span>My Upcoming Events</span>
          <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
        </button>
      </div>
      <div class="dropdown-menu" id="dropdown-menu" role="menu">
        <div class="dropdown-content">
          <ul>
            <% if @response == "You have not given the website permissions!" %>
              <div class="dropdown-item">
                <li><%= @response %></li>
              </div>
            <% else %>
              <% @response.items.each do |event| %>
                <% start = event.start.date || event.start.date_time %>
                <div class="dropdown-item">
                  <li><%= "#{event.summary} (#{start})" %></li>
                </div>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div>
      <br>
      <%= form_tag "/timesearch" do %>
        <p>Start:</p>
        <%= datetime_select :start_time, :start_time, {datetime_separator: " at ", :minute_step => 60, :discard_minute => true}, class: "select" %>
        :00
        <p>End:</p>
        <%= datetime_select :end_time, :end_time, {datetime_separator: " at ", :minute_step => 60, :discard_minute => true}, class: "select" %>
        :00
        <br><br>
        <%= submit_tag "Search", :class => "button is-medium is-primary" %>

      <% end %>
    </div>
    <br>
    <h2 class="title is-marginless">Available parking spots in this area <%= image_tag "google-pin.png", size: "18" %>
    </h2>
    <div id="localsList">
      <ul></ul>
    </div>
  </div>
</div>